medicos:
  path: /medicos
  controller: App\Controller\MedicosController::buscarTodos
  methods: 
    - GET

especialidades:
  path: /especialidades
  controller: App\Controller\EspecialidadesController::buscarTodos
  methods:
    - GET